"""initial schema

Revision ID: 20bd54d849de
Revises: 
Create Date: 2026-08-30 14:46:59.626391

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '20bd54d849de'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_table('handymen',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='handyman_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handymen_status'), 'handymen', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dispatcher', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('handyman_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('plumbing', 'electrical', 'hvac', 'carpentry', 'painting', 'appliance', 'general', 'other', name='task_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority'), nullable=False),
    sa.Column('status', sa.Enum('new', 'assigned', 'in_progress', 'done', 'cancelled', name='task_status'), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=16), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('time_window_start', sa.Time(), nullable=True),
    sa.Column('time_window_end', sa.Time(), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['handyman_id'], ['handymen.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_number')
    )
    op.create_index('ix_tasks_customer_id', 'tasks', ['customer_id'], unique=False)
    op.create_index('ix_tasks_handyman_scheduled', 'tasks', ['handyman_id', 'scheduled_date'], unique=False)
    op.create_index('ix_tasks_scheduled_date', 'tasks', ['scheduled_date'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('task_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('new', 'assigned', 'in_progress', 'done', 'cancelled', name='task_status'), nullable=True),
    sa.Column('to_status', sa.Enum('new', 'assigned', 'in_progress', 'done', 'cancelled', name='task_status'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_history_task_id'), 'task_status_history', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_history_task_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_scheduled_date', table_name='tasks')
    op.drop_index('ix_tasks_handyman_scheduled', table_name='tasks')
    op.drop_index('ix_tasks_customer_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_handymen_status'), table_name='handymen')
    op.drop_table('handymen')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # Alembic creates the enum types but never drops them, which makes a
    # downgrade -> upgrade round trip fail with "type already exists".
    for enum_name in (
        "task_status",
        "task_priority",
        "task_category",
        "handyman_status",
        "user_role",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
